# Generated by Django 2.2.5 on 2019-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191011_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('0', 'Customer'), ('1', 'Operator'), ('2', 'Manager')], default='2', max_length=10),
        ),
    ]
