# Generated by Django 2.2.5 on 2019-10-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191017_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Operator', 'Operator'), ('Manager', 'Manager')], default='Customer', max_length=10),
        ),
    ]
