# Generated by Django 2.2.5 on 2019-10-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191011_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amount_owed',
            field=models.FloatField(default=0.0),
        ),
    ]
