# Generated by Django 2.0.2 on 2019-10-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191017_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='current_location',
        ),
    ]
