# Generated by Django 2.2.5 on 2019-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_amount_owed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hire_in_progress',
        ),
        migrations.AddField(
            model_name='account',
            name='hires_in_progress',
            field=models.IntegerField(default=0),
        ),
    ]
