# Generated by Django 2.2.5 on 2019-10-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
