# Generated by Django 2.0.2 on 2019-10-01 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='check_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='due_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='station',
            name='station_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
