# Generated by Django 2.2.5 on 2019-10-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='station_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShare.Station'),
        ),
    ]
