# Generated by Django 2.2.5 on 2019-10-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0002_auto_20191017_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BikeShare.Station'),
        ),
    ]
