# Generated by Django 2.2.5 on 2019-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0002_auto_20191018_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
