# Generated by Django 2.0.2 on 2019-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0002_auto_20191001_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='current_usage',
        ),
        migrations.AddField(
            model_name='bike',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='is_faulty',
            field=models.BooleanField(default=False),
        ),
    ]
