# Generated by Django 2.2.5 on 2019-10-07 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BikeShare', '0003_auto_20191007_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='due_amount',
        ),
        migrations.RemoveField(
            model_name='previousorders',
            name='order',
        ),
        migrations.AddField(
            model_name='previousorders',
            name='bike',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BikeShare.Bike'),
        ),
        migrations.AddField(
            model_name='previousorders',
            name='check_out_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='previousorders',
            name='due_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='previousorders',
            name='start_station',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BikeShare.Station'),
        ),
        migrations.AddField(
            model_name='previousorders',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='previousorders',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='bike',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BikeShare.Bike'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
