# Generated by Django 2.0.2 on 2019-10-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0003_auto_20191001_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='bikeid',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='station',
            name='stationid',
        ),
    ]
