# Generated by Django 2.2.5 on 2019-10-07 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0004_auto_20191007_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousorders',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShare.Bike'),
        ),
    ]
