# Generated by Django 2.2.5 on 2019-10-07 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeShare', '0007_auto_20191007_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeShare.Order')),
            ],
            options={
                'verbose_name_plural': 'Previous Orders',
            },
        ),
    ]
